export default function isPreposition(word) {
  const prepositions = [
    'bis',
    'aus',
    'anstatt',
    'an',
    'durch',
    'außer',
    'statt',
    'auf',
    'entlang',
    'bei',
    'außerhalb',
    'hinter',
    'für',
    'dank',
    'innerhalb',
    'in',
    'gegen',
    'entgegen',
    'gegenüber',
    'jenseits',
    'neben',
    'je',
    'gemäß',
    'diesseits',
    'über',
    'ohne',
    'laut',
    'seitens',
    'unter',
    'um',
    'mit',
    'während',
    'vor',
    'wider',
    'nach',
    'wegen',
    'zwischen',
    'seit',
    'mithilfe',
    'von',
    'anhand',
    'zu',
  ];
  const regex = new RegExp('^' + prepositions.join('$|^') + '$', 'i');
  return regex.test(word);
}
